language: python
python:
 - "2.5"
 - "2.6"
 - "2.7"
# Someday, soon.
# - "3.2"
install: pip install --use-mirrors -e .
script: python setup.py test
notifications:
    email: false
    irc:
        - "irc.freenode.net#toscawidgets"
    on_success: change
    on_failure: always
